### ISSUE TITLE
Distancia euclidea entre tres punts

### ISSUE THREAD

**Issue by victor-prt** [gdsa-upc/102.1#63]
Hola @amaiasalvador i @xavigiro,

Hem aconseguit implementar un extractor de caracteristiques bassat en rootSIFT + SURF amb Late fusion, y ens hem trobat que a l'hora de calcular la distància euclidea no sabem bé del tot com fer-ho, ja que ara tenim dos BoW per cada imatge (un corresponent al rootSIFT i un altre corresponent al SURF). Creiem que la millor opcí sería calcular la distància euclidea entre la imatge de validació i el BoW tant de surf com de rootSIFT i agafar el valor més baix, però no estem segurs de que així estigui 100% bé. Ens podríeu donar una pista?gràcies per l'atenció

**Comment by amaiasalvador** [comment]
Hola Víctor,

has tancat l'issue, entenc que vol dir que està resolt?

En qualsevol cas, la distància final podria ser la mitja de les dues, la màxima, la mínima, ... Podeu també concatenar els dos vectors per tenir-ne un de sol i utilitzar-lo per calcular la distància a l'hora de fer el ranking o per entrenar un classificador.
